name: sync-to-jira
description: "Sync BMAD epics and stories to Jira (one-way push). Creates Jira Epics and Stories from sprint artifacts and tracks Jira issue keys in BMAD files."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/sync-to-jira"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/jira-sync-template.md"
validation: "{installed_path}/checklist.md"

# Variables and inputs
variables:
  # Project identification
  project_name: "{config_source}:project_name"

  # Jira configuration
  jira_cloud_id: "b8e4c3c2-d6c0-4770-95eb-64352aea65b8" # qedpartner.atlassian.net
  jira_project_key: "SCRUM"
  jira_epic_type_id: "10001"
  jira_story_type_id: "10004"

  # Source locations
  epics_location: "{sprint_artifacts}/epics"
  stories_location: "{sprint_artifacts}/stories"

  # Sync tracking
  sync_log: "{sprint_artifacts}/jira-sync-log.md"

# Smart input file references
input_file_patterns:
  epics:
    description: "Epic files in sprint artifacts"
    whole: "{sprint_artifacts}/epics/epic-*.md"
    load_strategy: "FULL_LOAD"
  stories:
    description: "Story files in sprint artifacts"
    whole: "{sprint_artifacts}/stories/story-*.md"
    load_strategy: "FULL_LOAD"

# Output configuration
default_output_file: "{sync_log}"

standalone: true
