/**
 * Supabase Database Types
 *
 * Re-exports types from the auto-generated database.types.ts
 * Generated by: npx supabase gen types typescript --project-id <project-id>
 *
 * Story: E1.3 - Create PostgreSQL Schema with RLS Policies
 */

// Re-export all types from generated file
export * from './database.types'

// Import Database type for convenience exports
import type { Database } from './database.types'

// Convenience type aliases for common table operations
export type Deal = Database['public']['Tables']['deals']['Row']
export type DealInsert = Database['public']['Tables']['deals']['Insert']
export type DealUpdate = Database['public']['Tables']['deals']['Update']

export type Document = Database['public']['Tables']['documents']['Row']
export type DocumentInsert = Database['public']['Tables']['documents']['Insert']
export type DocumentUpdate = Database['public']['Tables']['documents']['Update']

export type Finding = Database['public']['Tables']['findings']['Row']
export type FindingInsert = Database['public']['Tables']['findings']['Insert']
export type FindingUpdate = Database['public']['Tables']['findings']['Update']

export type Insight = Database['public']['Tables']['insights']['Row']
export type InsightInsert = Database['public']['Tables']['insights']['Insert']
export type InsightUpdate = Database['public']['Tables']['insights']['Update']

export type Conversation = Database['public']['Tables']['conversations']['Row']
export type ConversationInsert = Database['public']['Tables']['conversations']['Insert']
export type ConversationUpdate = Database['public']['Tables']['conversations']['Update']

export type Message = Database['public']['Tables']['messages']['Row']
export type MessageInsert = Database['public']['Tables']['messages']['Insert']
export type MessageUpdate = Database['public']['Tables']['messages']['Update']

export type Irl = Database['public']['Tables']['irls']['Row']
export type IrlInsert = Database['public']['Tables']['irls']['Insert']
export type IrlUpdate = Database['public']['Tables']['irls']['Update']

export type QaList = Database['public']['Tables']['qa_lists']['Row']
export type QaListInsert = Database['public']['Tables']['qa_lists']['Insert']
export type QaListUpdate = Database['public']['Tables']['qa_lists']['Update']

export type Cim = Database['public']['Tables']['cims']['Row']
export type CimInsert = Database['public']['Tables']['cims']['Insert']
export type CimUpdate = Database['public']['Tables']['cims']['Update']

// Auth user type (from Supabase Auth)
export interface AuthUser {
  id: string
  email?: string
  email_confirmed_at?: string
  phone?: string
  confirmed_at?: string
  last_sign_in_at?: string
  app_metadata: {
    provider?: string
    providers?: string[]
  }
  user_metadata: {
    avatar_url?: string
    email?: string
    email_verified?: boolean
    full_name?: string
    iss?: string
    name?: string
    picture?: string
    provider_id?: string
    sub?: string
  }
  created_at: string
  updated_at?: string
}
